# Taps
#
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Brew formulae
#
# brew "ack"
# brew "antigen"
# brew "sqlite"
# brew "awscli"
# brew "b2-tools"
# brew "bat"
# brew "certbot"
# brew "fd"
# brew "ffmpeg"
# brew "fzf"
brew "git"
# brew "htop"
# brew "id3v2"
# brew "mas"
# brew "media-info"
# brew "nmap"
# brew "nvm"
# brew "psgrep"
# brew "pstree"
# brew "pyenv-virtualenv"
# brew "rclone"
# brew "ripgrep"
# brew "rust"
# brew "speedtest-cli"
# brew "starship"
# brew "telnet"
# brew "timedog"
# brew "tree"
# brew "truncate"
# brew "unrar"
# brew "zsh"

# Casks
#
# cask "1clipboard"
# cask "1password"
# cask "adobe-acrobat-reader"
# cask "alfred"
cask "anki"
# cask "appcleaner"
# cask "arq"
# cask "aurora-hdr"
# cask "bettertouchtool"
# cask "betterzip"
# cask "cleanmymac"
# cask "daisydisk"
# cask "dropbox"
# cask "fantastical"
# cask "fastrawviewer"
# cask "firefox"
# cask "font-anonymice-powerline"
# cask "font-consolas-for-powerline"
# cask "font-dejavu-sans-mono-for-powerline"
# cask "font-droid-sans-mono-for-powerline"
# cask "font-fira-mono-for-powerline"
# cask "font-inconsolata-dz-for-powerline"
# cask "font-inconsolata-for-powerline"
# cask "font-inconsolata-for-powerline-bold"
# cask "font-inconsolata-g-for-powerline"
# cask "font-liberation-mono-for-powerline"
# cask "font-menlo-for-powerline"
# cask "font-meslo-for-powerline"
# cask "font-monofur-for-powerline"
# cask "font-noto-mono-for-powerline"
# cask "font-roboto-mono-for-powerline"
# cask "font-source-code-pro-for-powerline"
# cask "font-ubuntu-mono-derivative-powerline"
# cask "google-chrome"
# cask "gpgtools"
# cask "iterm2"
# cask "karabiner-elements"
# cask "keybase"
# cask "kid3"
# cask "kindle"
# cask "numi"
# cask "nvalt"
# cask "osxfuse"
# cask "plex-media-player"
# cask "qlcolorcode"
# cask "qlmarkdown"
# cask "qlstephen"
# cask "quicklook-json"
# cask "photosync"
# cask "private-internet-access"
# cask "qfinder-pro"
# cask "sonos"
# cask "soulver"
# cask "spectacle"
# cask "spotify"
# cask "sublime-text"
# cask "teamviewer"
# cask "textual"
# cask "timemachineeditor"
# cask "thingsmacsandboxhelper"
# cask "transmit"
# cask "ubiquiti-unifi-controller"
# cask "unetbootin"
# cask "vanilla"
# cask "viscosity"
# cask "vlc"
# cask "vox"
# cask "xee"
# cask "zoom"

# Apple Store apps
#
mas "Bear", id: 1091189122
# mas "Disk Speed Test", id: 425264550
# mas "Display Maid", id: 450063525
# mas "GarageBand", id: 682658836
# mas "iMovie", id: 408981434
# mas "Keynote", id: 409183694
# mas "Microsoft Remote Desktop", id: 1295203466
# mas "Monosnap", id: 540348655
# mas "Numbers", id: 409203825
# mas "Pages", id: 409201541
# mas "Slack", id: 803453959
# mas "The Unarchiver", id: 425424353
# mas "Things", id: 904280696
# mas "uBlock", id: 1385985095
# mas "Unsplash Wallpapers", id: 1284863847
# mas "Vimari", id: 1480933944
