# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_DISABLE_COMPFIX="true"

source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

#antigen bundle autojump
antigen bundle brew
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle git
antigen bundle git-extras
antigen bundle osx
antigen bundle z
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh

antigen theme romkatv/powerlevel10k
#antigen theme gnzh
#antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

antigen apply

source /Users/andrei/.zsh/aliases.sh
source /Users/andrei/.zsh/env.sh
source /Users/andrei/.zsh/functions.sh
source /Users/andrei/.zsh/nvm.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
