ZSH_DISABLE_COMPFIX="true"

source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

#antigen bundle autojump
antigen bundle brew
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle git
antigen bundle git-extras
antigen bundle osx
antigen bundle z
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh

#antigen theme gnzh
#antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

antigen apply

eval "$(starship init zsh)"

source /Users/andrei/.zsh/aliases.sh
source /Users/andrei/.zsh/env.sh
source /Users/andrei/.zsh/functions.sh
source /Users/andrei/.zsh/nvm.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
